/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author Regular Vahn
 */
public class Handlersettings extends javax.swing.JFrame {

    /**
     * Creates new form Handlersettings
     */
    public Handlersettings() {
        initComponents();
        HandlerinitComponents();
    }

    private void HandlerinitComponents(){
        JPasswordField password = new JPasswordField();
        this.add(password);
        password.setLocation(0,0);
        try{
        BufferedReader br = new BufferedReader(new FileReader("settings.txt"));
        try {
        StringBuilder sb = new StringBuilder();
        Textfieldhost.setText(br.readLine());
        Textfielddatabase.setText(br.readLine());
        Textfieldusername.setText(br.readLine());
        Textfieldpassword.setText(br.readLine());
        Textfieldcst.setText(br.readLine());
        Textfieldcft.setText(br.readLine());
        Textfieldast.setText(br.readLine());
        } finally {
        br.close();
        }
           }catch(Exception e)
           {
               
           }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Labelhost = new javax.swing.JLabel();
        Labeldatabase = new javax.swing.JLabel();
        Labelusername = new javax.swing.JLabel();
        Labelpassword = new javax.swing.JLabel();
        Textfieldhost = new javax.swing.JTextField();
        Textfielddatabase = new javax.swing.JTextField();
        Textfieldusername = new javax.swing.JTextField();
        Textfieldpassword = new javax.swing.JTextField();
        Buttonsave = new javax.swing.JButton();
        Buttonexit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Textfieldcft = new javax.swing.JTextField();
        Textfieldast = new javax.swing.JTextField();
        Textfieldcst = new javax.swing.JTextField();
        Buttonload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Labelhost.setText("Host : ");

        Labeldatabase.setText("Database : ");

        Labelusername.setText("Username : ");

        Labelpassword.setText("Password : ");

        Buttonsave.setText("Save Settings");
        Buttonsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonsaveActionPerformed(evt);
            }
        });

        Buttonexit.setText("Exit");
        Buttonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonexitActionPerformed(evt);
            }
        });

        jLabel1.setText("Clustering Student Table:");

        jLabel2.setText("Clustering Faculty Table:");

        jLabel3.setText("Association Student Table:");

        Textfieldast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldastActionPerformed(evt);
            }
        });

        Buttonload.setText("Load Settings");
        Buttonload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Buttonsave)
                        .addGap(18, 18, 18)
                        .addComponent(Buttonload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buttonexit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(Textfieldcft))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(Textfieldast))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Labelusername)
                            .addComponent(Labeldatabase)
                            .addComponent(Labelhost)
                            .addComponent(Labelpassword))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Textfieldpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(Textfieldhost)
                            .addComponent(Textfielddatabase)
                            .addComponent(Textfieldusername, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(Textfieldcst)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labelhost)
                    .addComponent(Textfieldhost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labeldatabase)
                    .addComponent(Textfielddatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labelusername)
                    .addComponent(Textfieldusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labelpassword)
                    .addComponent(Textfieldpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Textfieldcst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Textfieldcft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(Textfieldast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buttonsave)
                    .addComponent(Buttonexit)
                    .addComponent(Buttonload))
                .addContainerGap())
        );

        Textfieldpassword.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
private String
    path = "C:\\Users\\Regular Vahn\\Documents\\NetBeansProjects\\jTableTestTwo.settings.txt";
private Boolean
        append_to_file=false;
      
public void saveSettings()throws IOException{
    try{
    //FileWriter file = new FileWriter(path,append_to_file);
    System.out.println("Establishing FileWriter");
    PrintWriter print_line = new PrintWriter("settings.txt");
    System.out.println("Establishing PrintWriter");
    File newSettings = new File("settings.txt");
    System.out.println("Establishing File");
    
    String value;
    System.out.println("Established String");
    FileWriter fw = new FileWriter(newSettings);
    System.out.println("Established FileWriter");
    value = Textfieldhost.getText();
    System.out.println("Established value");
    fw.write(value+"\n");
    System.out.println("Established write");
    //print_line.printf("%s"+"%n", value);
     value = Textfielddatabase.getText();
      fw.write(value+"\n");
    // print_line.printf("%s"+"%n", value);
      value = Textfieldusername.getText();
       fw.write(value+"\n");
     // print_line.printf("%s"+"%n", value);
       value = Textfieldpassword.getText();
        fw.write(value+"\n");
      // print_line.printf("%s"+"%n", value);
       value = Textfieldcst.getText();
        fw.write(value+"\n");
     //  print_line.printf("%s"+"%n", value);
       value = Textfieldcft.getText();
        fw.write(value+"\n");
     //  print_line.printf("%s"+"%n", value);
       value = Textfieldast.getText();
        fw.write(value+"\n");
    //   print_line.printf("%s"+"%n", value);
       
     //  print_line.close();
        fw.close();
       
       JOptionPane.showMessageDialog(null, "Saved Settings", "Saved", JOptionPane.INFORMATION_MESSAGE);
    }catch(IOException e)
    {
        JOptionPane.showMessageDialog(null, "IO Exception", "Error", JOptionPane.INFORMATION_MESSAGE);
    }
}
        

    private void ButtonsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonsaveActionPerformed

        try {
            saveSettings();
        } catch (IOException ex) {
            Logger.getLogger(Handlersettings.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_ButtonsaveActionPerformed

    private void ButtonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonexitActionPerformed

        Mainmenu menu = new Mainmenu();
        //menu.setVisible(true);
        menu.requestFocusInWindow();
        menu.setLocationRelativeTo(null); 
        this.dispose();
        
    }//GEN-LAST:event_ButtonexitActionPerformed

    private void TextfieldastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextfieldastActionPerformed

    private void ButtonloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonloadActionPerformed
        // TODO add your handling code here:
        try{
        BufferedReader br = new BufferedReader(new FileReader("settings.txt"));
        try {
        StringBuilder sb = new StringBuilder();
        Textfieldhost.setText(br.readLine());
        Textfielddatabase.setText(br.readLine());
        Textfieldusername.setText(br.readLine());
        Textfieldpassword.setText(br.readLine());
        Textfieldcst.setText(br.readLine());
        Textfieldcft.setText(br.readLine());
        Textfieldast.setText(br.readLine());
        } finally {
        br.close();
        }
           }catch(Exception e)
           {
               
           }
    }//GEN-LAST:event_ButtonloadActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Handlersettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Handlersettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Handlersettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Handlersettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Handlersettings().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonexit;
    private javax.swing.JButton Buttonload;
    private javax.swing.JButton Buttonsave;
    private javax.swing.JLabel Labeldatabase;
    private javax.swing.JLabel Labelhost;
    private javax.swing.JLabel Labelpassword;
    private javax.swing.JLabel Labelusername;
    private javax.swing.JTextField Textfieldast;
    private javax.swing.JTextField Textfieldcft;
    private javax.swing.JTextField Textfieldcst;
    private javax.swing.JTextField Textfielddatabase;
    private javax.swing.JTextField Textfieldhost;
    private javax.swing.JTextField Textfieldpassword;
    private javax.swing.JTextField Textfieldusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
